name: check-docs
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build moonwave docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm i -g moonwave@latest
      - name: Build docs
        run: moonwave build --code src
